export const KURULUS__LIST_REQUEST = 'KURULUS__LIST_REQUEST'
export const KURULUS__LIST_SUCCESS = 'KURULUS__LIST_SUCCESS'
export const KURULUS__LIST_FAIL = 'KURULUS__LIST_FAIL'

export const KURULUS__DETAILS_REQUEST = 'KURULUS__DETAILS_REQUEST'
export const KURULUS__DETAILS_SUCCESS = 'KURULUS__DETAILS_SUCCESS'
export const KURULUS__DETAILS_FAIL = 'KURULUS__DETAILS_FAIL'


export const KURULUS__DELETE_REQUEST = 'KURULUS__DELETE_REQUEST'
export const KURULUS__DELETE_SUCCESS = 'KURULUS__DELETE_SUCCESS'
export const KURULUS__DELETE_FAIL = 'KURULUS__DELETE_FAIL'

export const KURULUS__CREATE_REQUEST = 'KURULUS__CREATE_REQUEST'
export const KURULUS__CREATE_SUCCESS = 'KURULUS__CREATE_SUCCESS'
export const KURULUS__CREATE_FAIL = 'KURULUS__CREATE_FAIL'
export const KURULUS__CREATE_RESET = 'KURULUS__CREATE_RESET'


export const KURULUS__UPDATE_REQUEST = 'KURULUS__UPDATE_REQUEST'
export const KURULUS__UPDATE_SUCCESS = 'KURULUS__UPDATE_SUCCESS'
export const KURULUS__UPDATE_FAIL = 'KURULUS__UPDATE_FAIL'
export const KURULUS__UPDATE_RESET = 'KURULUS__UPDATE_RESET'