# Generated by Django 4.2.1 on 2023-06-02 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takip',
            fields=[
                ('kurulus_adi', models.CharField(blank=True, max_length=200, null=True)),
                ('kurulus_logo', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('kurulus_turu', models.CharField(blank=True, max_length=200, null=True)),
                ('ulke', models.CharField(blank=True, max_length=200, null=True)),
                ('web_site', models.TextField(blank=True, null=True)),
                ('calisan_sayisi', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('takip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kurulus',
            fields=[
                ('kurulus_adi', models.CharField(blank=True, max_length=200, null=True)),
                ('kurulus_logo', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('kurulus_turu', models.CharField(blank=True, max_length=200, null=True)),
                ('ulke', models.CharField(blank=True, max_length=200, null=True)),
                ('web_site', models.TextField(blank=True, null=True)),
                ('calisan_sayisi', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
